### ISSUE TITLE
Chrome Extension to Close Unwanted Zoom Windows Proposal

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/futureautomations#10]
### Overview 
We need a chrome extention that automatically closes zoom windows (e.g., https://us04web.zoom.us/postattendee?id=7, https://us02web.zoom.us/postattendee?id=5, etc.)

### Problem being solved
Anyone who uses Zoom regularly has to close the window that opens after the meeting starts.  If you do many Zoom meetings every day, it's a big time waster.

### Current State ("as is")
The windows must be closed automatically.

### Future Development ("future state")
A chrome extension that watches for urls that contain "zoom.us/postattendee" and closes them automatically.

### Action Items/Research
TBD

### Stakeholders
People who use Zoom a lot (Bonnie, other people who have a lot of meetings)

### Anticipated outcomes
Saving time closing windows.

### Resources/Instructions
[How to create a chrome extension tutorial - not necessarily the right tutorial though](https://www.sitepoint.com/create-chrome-extension-10-minutes-flat/)
[Making Chrome extension run in the background](https://developer.chrome.com/extensions/background_pages)

### Language
Javascript

### Platform
Chrome Extension

### Automation triggers (What starts it? What's it responding to?)
Figure out the way to do the listening so that it doesn't slow down the system.

### Input required (How much manual or custom input is required?)
TBD

### Output 
Closes unnecessary windows without slowing down the system.

### Project size
Medium

**Comment by Olivia-Chiong** [comment]
This already exists.
