### ISSUE TITLE
Civil Server Proposal

### ISSUE THREAD

**Issue by ddfridley** [100Automations/futureautomations#16]
**In bold, I create come new things for your template**
### Overview 
_What kind of repetitive thing do you have to do often and what is the benefit of automating it?_
When I build a project that requires user logins, it's a lot of work, and you have to be very careful about security.  Also, there are some specific to civic tech projects, like getting users voting districts, and validating users are in that district that are different from other projects.  Also, the Civic Tech space has a lot of people working independently and it would help us all if there were some things we could work together on.  This could be one of them.

### Ownership of Idea
- [x] **I will be working on the automation and I'm looking for others**
- [ ] I will be working on this automation myself
- [ ] This is my idea and I need help developing it
- [ ] Free for anyone to work on this idea

### Current State 
_"As-is" most likely something manual but could be partially automated_
There is a repo that I have started at https://github.com/EnCiv/civil-server

### **Current Alternatives/Competitors** I added this
https://www.meteor.com/
Here was a great comparison of API's that are commercial:
https://everydeveloper.com/apis/user-login/
Including Oauth, Janrain, LoginRadius, OAuth0.io, Stormpath

### Future Development
- using [passport.js](http://www.passportjs.org/) for authentication
- using the civic info API to get a voter's district info
- validating the user is in that district through gps from their phone
- finding a way to work with rockthevote api's to validate a users' address, and that they are registered to vote

### Stakeholders
_Impact - who benefits and how?_
Civic Tech platform developers - not having to reinvent the wheel, sharing efforts
Other Nextdoor like projects - not having to reinvent the wheel 

### Anticipated outcomes
Quicker to develop web portals that require user accounts

### Resources/Instructions
**some explanation needed here**

### Language
Javascript

### Platform
Node, Mongo, React

### Automation triggers (What starts it? What's it responding to?)
- _Time-based (Specify frequency (e.g. 1x/week)_
- _Event-based (e.g. someone just created a new GitHub on a repo)_
Developing a new platform

### Input required (How much manual or custom input is required?)
developers would npm install civil-server or git clone github.com/EnCiv/civil-server-template depending on their path.  Then they would follow the instructions to adapt it for their application. 

### Output 
_(What's the desired result? What do we not want to see?)_
Lots of Civic Tech Projects using this, and building the killer apps that save the world. 

### Project size
Large

**Comment by ExperimentsInHonesty** [comment]
@ddfridley Hi David.  I know this is crazy, but we had a problem with the automation proposal process and didn't even see this until now... More than a year later.

We think this is an awesome idea, however it's more service than automation.  The company that I can think of that has the expertise in this space, could potentially take on something this big and that might be interested would be [Civic Software Foundation](https://civicsoftwarefoundation.org/).

**Comment by ddfridley** [comment]
thanks. I'll check them out.
