### ISSUE TITLE
Automation Proposal: GHA-add-issue-to-project

### ISSUE THREAD

**Issue by 100AutomationsProject** [100Automations/futureautomations#47]
## Your Name
Ava Li

## Your Email
avali4907@outlook.com

## Overview: describe the kind of repetitive thing you have to do and the benefit of automating it?
Often times, when an issue is created, it should move into the project board, where it can be organized. If an issue is not moved into the project board, or worse, moved into the wrong project board or wrong column, development and work on a project is stalled. By automatically placing newly created issues into an appropriate place, errors are lessened, and project workflow can be focused less on organizing the project, and more on delivering a product.

## Ownership of Idea
I will be working on this automation myself

## Current State: Is this just an idea, or has any work already been done to build it?
The automation is currently finished.

## Languages or frameworks used?
yml, javascript

## Platform?
GitHub

## Automation triggers: What starts it? What's it responding to? Time or event based?
That depends on what trigger the user wants it to be. It is customizable. The automation simply move issues based on a trigger.

Any [GHA trigger](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows) can technically trigger it, if customized to do so.  The current triggers that will cause it to run are:
- issue comment created
- issue comment edited
- issue comment deleted
- issue opened
- issue edited
- issue deleted
- issue transferred
- issue pinned
- issue unpinned
- issue closed
- issue reopened
- issue assigned
- issue unassigned
- issue labeled
- issue unlabeled
- issue locked
- issue unlocked
- issue milestoned
- issue demilestoned

### Examples of what this can do, include:
- Place the issue in the 'Dependency' column if the dependency label is added.
- If the issue has the phrase, "Research and Development" in the body, move it into the "R&D" column of the "Research" project.

## How much manual or custom input is required?
There needs to be an initial configuration and setup before it can run automatically.

## Output: What's the desired result? What do we not want to see?
The desired result is to have the automation be easy to use, setup, and customize. We want to reduce the amount of work that goes into organizing and managing the project board.

## Project size: rough estimate of effort and time needed to build it
It can be on-going as additional features are requested.

## Stakeholders and Impact - who benefits and how?
Anyone who manages a github project board will benefit. The impact of this is directly proportional to the size of a project.

## Resources/Instructions: Has any documentation been created yet?
Yes

## Action Items/Research Needed
None. Everything is already set.

## Bio of author
- https://github.com/100Automations/Website/issues/503

## Health files
- [x] https://github.com/100Automations/GHA-add-issue-to-project/blob/master/CODE_OF_CONDUCT.md
- [x] https://github.com/100Automations/GHA-add-issue-to-project/blob/master/CONTRIBUTING.md
- [x] https://github.com/100Automations/GHA-add-issue-to-project/blob/master/SECURITY.md
- [x] https://github.com/100Automations/GHA-add-issue-to-project/blob/master/README.md
- [x] https://github.com/100Automations/GHA-add-issue-to-project/blob/master/SUPPORT.md
- [x] license

## Name of Repo
- https://github.com/100Automations/GHA-add-issue-to-project

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art

Re the question and your answer
Q; Automation triggers: What starts it? What's it responding to? Time or event based?
A: That depends on what trigger the user wants it to be. It is customizable. The automation simply move issues based on a trigger.

Can you enumerate the types of triggers it can use?

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art Do you want us to create the repo that has the [default health files](https://100automations.org/guides/community-support-for-automations.html) in it, or do you want to fork the repo to us, and then add those files after?

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art we are trying to decide on a name for the repository (which we could change later),
1. does _GHA-add-issue-to-project_ seem like a good name?
2. do you have something else in mind?
3. should we use that as the working title and focus on the name later?

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty 

As of right now, any trigger will technically trigger it, but in terms of actually getting it to work as intended, these are the triggers that can cause it to run:

- issue comment created
- issue comment edited
- issue comment deleted
- issue opened
- issue edited
- issue deleted
- issue transferred
- issue pinned
- issue unpinned
- issue closed
- issue reopened
- issue assigned
- issue unassigned
- issue labeled
- issue unlabeled
- issue locked
- issue unlocked
- issue milestoned
- issue demilestoned

For the repo, I can transfer ownership of the automation from my repo to 100automations and then add the health files. That might be the simplest and cleanest way of doing this!

For the title, for now it is "miniature-octo-sniffle". I'm not obviously attached to it, so if the 100automations team wishes to change it to "GHA-add-issue-to-project", or variations thereof, I do not mind, once the transfer is completed.

**Comment by ExperimentsInHonesty** [comment]
We have made you an owner of the github org temporarily so that you can fork the repo to 100automations github.  Here is the [healthfiles instructions](https://100automations.org/guides/community-support-for-automations.html) so that you can copy and customize those when you are done.

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art could you also [give us a bio](https://github.com/100Automations/Website/issues/new?assignees=&labels=role%3A+content+writing%2C+role%3A+marketing&template=write-bio---content-creator-template.md&title=Write+Bio+-+Content+Creator%3A+%5BINSERT+NAME%5D), please

**Comment by Aveline-art** [comment]
> @Aveline-art
> 
>     1. We have made you an owner of the github org temporarily so that you can fork the repo to 100automations github.
> 
>     2. Here is the [healthfiles instructions](https://100automations.org/guides/community-support-for-automations.html) so that you can copy and customize those when you are done.
> 
>     3. Next steps
>        
>        * [x]  Please assign this issue to yourself
>        * [x]  let us know when you are done with the forking
>          
>          * [ ]  we will make you the repo admin for that repo
>        * [x]  let us know when you are done with the adding health files by moving this to the review column
>          
>          * [ ]  we will review the repo to see if we have any additional requests.
> 
> 
> Thanks!!! So excited for you to add this

The [repo ](https://github.com/100Automations/miniature-octo-sniffle)has been moved to the organization with the healthfile templates and a [bio ](https://github.com/100Automations/Website/issues/503)has been made.

**Comment by henlatourrette** [comment]
Thank you @Aveline-art ! I'm unassigning you from this issue temporarily as we will now review it and decide on the next steps.

@ExperimentsInHonesty I'm assigning it to you and me so that we move forward with the reviewing phase.

**Comment by henlatourrette** [comment]
Thanks @Aveline-art  for all your hard work so far! Please review our notes below. We look forward to our next review of this valuable automation you have provided

This guide will help you customize the health documents that come with your repo. You can see examples we have provided in the guide: https://100automations.org/guides/community-support-for-automations.html

https://github.com/100Automations/miniature-octo-sniffle/blob/master/CODE_OF_CONDUCT.md
https://github.com/100Automations/miniature-octo-sniffle/blob/master/CONTRIBUTING.md -> needs to be customized.
https://github.com/100Automations/miniature-octo-sniffle/blob/master/SECURITY.md -> needs to be customized.
https://github.com/100Automations/miniature-octo-sniffle/blob/master/SUPPORT.md -> needs to be customized.

https://github.com/100Automations/miniature-octo-sniffle/blob/master/README.md -> It needs more context:
The people coming to this repo won't understand what column you are referring to.  Please see the details you provided in this issue https://github.com/100Automations/futureautomations/issues/47, for reference

**Comment by ExperimentsInHonesty** [comment]
I asked @Aveline-art for a potential change to the bio, will check any updates on that next time we review this issue  https://github.com/100Automations/Website/issues/503#issuecomment-1012666502

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art has updated the bio.

**Comment by Aveline-art** [comment]
**Update:** I have updated the health files and completed all of them, including the Readme. One pain point is that I could not simply copy and paste the above proposal into the Readme, as I did not have edit permissions. As such, I could not copy and paste all the MarkDown formatting that existed in the original proposal.

**Comment by henlatourrette** [comment]
Hey @Aveline-art. I'm sorry for that. We've given you write access to the FutureAutomations repo in case you need it in the future.

We'll be reviewing your submission and get back to you shortly.

**Comment by henlatourrette** [comment]
Here are our notes from the review of your "README.md":

- It has the old name "Miniature Octo Sniffle action", please update it
- In this sentence "Any GHA trigger can technically trigger it, but most would result in an error. The triggers that work best are:" Here's our question about it: 
 Do you mean that you haven't coded other triggers and therefore, using them would generate an error? or.. do you mean if you code it other triggers, it's would not be feasible so you would receive an error.

**Comment by ExperimentsInHonesty** [comment]
Hi @Aveline-art Henry and I have a minor change request on this file [SECURITY.md](https://github.com/100Automations/GHA-add-issue-to-project/blob/master/SECURITY.md)

Where it says 
> Feel free to drop into the 100 Automations Slack (or @ mention me (@Ava Li)) to report any vulnerabilities.

Please change it to 
Feel free to @ mention me, (Ava Li) by dropping into the 100 Automations Slack channel to report any vulnerabilities.

**Comment by Aveline-art** [comment]
Hi @henlatourrette @ExperimentsInHonesty . Thank you so much for this feedback! I have made the corrections as a pull request. Changes can be viewed [here](https://github.com/100Automations/GHA-add-issue-to-project/pull/16/files). The updated README.md can be viewed [here](https://github.com/100Automations/GHA-add-issue-to-project/blob/e13497db6cf41bf3cf2c700592faa9d7c5d4cc97/README.md). If needed, the current README can be viewed [here](https://github.com/100Automations/GHA-add-issue-to-project#readme).

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art I have approved the PR, ill leave it to you to Merge it.

**Comment by henlatourrette** [comment]
@Aveline-art  After you merge those changes, all that remains is to help us make it appear on the 100Automations.org website. In order, to facilitate that we have created a guide for what is required:
https://100automations.org/guides/prep-automation-for-publication.html

Unfortunately, we don't have graphic designers to help us with the logo. Let us know if you want to brainstorm a hacky version similar to what Bonnie has created for "Jekyll Gather Data Types" and "True Github contributors" which you can see on the 100Automations homepage.

Please use the issue template contained in the guide to submitting your content.

**Comment by Aveline-art** [comment]
@henlatourrette Thanks for letting me know the next steps. For the logo, is there a standard 100automations logo. I'm thinking my automation can fall into some 100automations branding or what no?

**Comment by Aveline-art** [comment]
@henlatourrette 

After reviewing the guide on my next steps, I find the page to be a little disorienting. It is hard to make out headings from sub headings, and took me a while to fully understand. For the description I would like to use the intro from the repo:

"If your team uses GitHub project boards to manage your repository's issues, making sure that all issues end up on the right board is crucial. If an issue is not moved into the project board, or worse, moved into the wrong project board or wrong column, development and work on a project is stalled. By automatically placing newly created issues into an appropriate place, errors are lessened, and project workflow can be focused less on organizing the project, and more on delivering a product.

This GitHub Action (GHA), when triggered, is designed to move issues to a specific column based on certain set of criteria such as a specific label, or specific phrase in the issue's body. This will prove helpful for members of a team who manages a project, such as project managers. By design, it abstracts a lot of the configuration into one file, making customization simple for team members who are not adept to coding syntax."

As for the status, I would say it is in development and needs peer review and user testing. That said, I am using it as a beta for CivicTechJobs at the moment. Should this information be included in the description?

**Comment by henlatourrette** [comment]
Hey @Aveline-art, we're working on a logo with Bonnie to help you out with that part. You can take a look at it here - slide number 6 :

https://docs.google.com/presentation/d/1D6GoIlHxmFqiMLeY2XXbLQY-al53xdRtBihj6FM2IhE/edit#slide=id.g11471637adc_0_60

Also, we noticed that your description has 900+ characters which is much more than the longest one we have right now on the site (536 characters). Do you think you can shrink it down a little bit? I think that the second paragraph has the key information about it. For full details, there will always be the ReadMe page. 

Regarding your questions about the current status, this should make it easier for you to pick - we don't have "needs user testing" as an option.

Possible Status of project: (must pick one)
- [ ] In Use And Ready To Deploy
- [ ] In Use and Needs Further Development
- [ ] In Use And Being Refactored
- [ ] Ready To Deploy
- [x] In Development
- [ ] Ready For Development
- [ ] In Ideation
- [ ] Abandoned

Needs Help status: (can pick as many as apply)
- [ ] Needs Maintenance
- [ ] Needs Support For Users
- [ ] Needs Refactoring
- [ ] Needs Documentation
- [x] Needs Peer Review
- [ ] Needs To Be Built
- [ ] Needs To Be Researched
- [ ] Needs Advice
- [ ] Needs Takeover
- [ ] Advice Needed

If you're using it on CivicTechJobs right now, it could say "As seen on CivicTechJobs" at the botton.

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art 
Here is the image we ended up making.  Let us know what you think.
![GHA-Add-Issue-to-Project](https://user-images.githubusercontent.com/37763229/154739117-e66f1990-0bd6-440a-ac8b-314fe1b939b5.PNG)

@henlatourrette fyi

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty It looks great! Kudos to the team member who created it!

---

I'll collect all the next step requirements below so that I can edit it all in once place:

#### Logo

See [here](https://github.com/100Automations/futureautomations/issues/47#issuecomment-1044952564).

#### Description

This GitHub Action (GHA), is designed to move issues to a specific column based on criteria such as a specific label, or specific phrase in the issue's body. This will prove helpful for members of a team who manages a GitHub project board, such as project managers, by lessening errors and organizing workflow. By design, it abstracts a lot of the configuration into one file, making customization simple for team members who are not adept to coding syntax."

#### Status

Status of project: (must pick one)
- [ ] In Use And Ready To Deploy
- [ ] In Use and Needs Further Development
- [ ] In Use And Being Refactored
- [ ] Ready To Deploy
- [x] In Development
- [ ] Ready For Development
- [ ] In Ideation
- [ ] Abandoned

Needs Help status: (can pick as many as apply)
- [ ] Needs Maintenance
- [x] Needs Support For Users
- [x] Needs Refactoring
- [ ] Needs Documentation
- [x] Needs Peer Review
- [ ] Needs To Be Built
- [ ] Needs To Be Researched
- [x] Needs Advice
- [ ] Needs Takeover
- [x] Advice Needed

#### Extra

Currently in use at CivicTechJobs.

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art We have added your automation to the 100automations website, but it looks like the part where it displays the project it's in use on is hard coded with a logo right now.  If you can work with the designers on CTJ to get their favicon, we can use that, and we will try to get some developers to fix our code so that it shows up properly on your card.

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty Certainly! The favicon can be found [here](https://github.com/hackforla/CivicTechJobs/blob/main/frontend/src/assets/images/svgs/logo-logomark.svg). The team can either use the link as is or import the asset into the 100auto repo.

**Comment by henlatourrette** [comment]
Thank you @Aveline-art! With this last update, I think we can consider it published and the process finished.

@ExperimentsInHonesty for the "as seen in" part I believe it should be considered as a bug on our website and treated separately. Or at least, we could leave it ready on the automation card but work with developers to fix it independently.
