### ISSUE TITLE
Create automation card for GHA Add Issue to Project

### ISSUE THREAD

**Issue by henlatourrette** [100Automations/futureautomations#48]
### Overview
Provide collateral for the OpenSourceAutomations.org website

### Action Items
- [x]   Gather items
  - [x]  744 x 300 image (The project image is 744 x 300 pixels, but displays at half that size, so it needs to be a clear, simple identifier of your automation.)
     - [x]  Alt image text
  - [x]  Name of automation
  - [x]  A blurb about the automation
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x] Healthy project files (see resources for instructions)
     - [x]  Readme.md URL
     - [x]  contributing.md URL
     - [x]  security.md URL
     - [x]  support.md URL
    - [x]  If you are looking for collaborators - What you are looking for skills wise
  - [x]  Status (in use, depreciated, needs update - and any other status you can think of)
     - [x] If status in use, what codebase can it be seen in?
- [x]   Add automation Card to website

### Resources/Instructions
See project cards on the hackforla.org website for general idea, although the format of these will be different.

- [GitHub's guide: Setting guidelines for repository contributors](https://docs.github.com/en/articles/setting-guidelines-for-repository-contributors)
- [GitHub's guide: Adding a security policy to your repository
](https://docs.github.com/en/articles/adding-a-security-policy-to-your-repository)
- [GitHub's guide: Adding support resources to your project
](https://docs.github.com/en/articles/adding-support-resources-to-your-project)

**Readme should include:**
- Overview 
  - _What kind of repetitive thing do you have to do often and what is the benefit of automating it?_
- Current State 
  - _"As-is" most likely something manual but could be partially automated_
- Future Development
  - _The “To-be” state_
- Stakeholders
  - _Impact - who benefits and how?_
- Anticipated outcomes
- Resources/Instructions
  - _How to run the automation and any packages or dependencies_ 
- Languages and Technologies
  - _Programming language(s)_
  - _Framework(s)_
- Platform
  - _Where is it deployed (e.g. GitHub, Linux Command Line, Windows Command Line etc)_
- Automation triggers 
  - _What starts it? What's it responding to?
  - _Is it Time-based (Specify frequency (e.g. 1x/week)?_
  - _Is it Event-based (e.g. someone just created a new GitHub on a repo)?_
- Input required 
  - _How much manual or custom input is required?_
- Output 
  - _What's the desired result? What do we not want to see?_

**Comment by henlatourrette** [comment]
---
identification: 436353836
title: GHA Add Issue to Project
description: This GitHub Action (GHA), is designed to move issues to a specific column based on criteria such as a specific label, or specific phrase in the issue's body. This will prove helpful for members of a team who manages a GitHub project board, such as project managers, by lessening errors and organizing workflow. By design, it abstracts a lot of the configuration into one file, making customization simple for team members who are not adept to coding syntax.
image: 'assets/images/projects/GHA-add-issue-to-project-hero.png'
alt: 'Emoji Cry before Emoji Happy After'
Authors:
- name: Ava Li
  links:
    slack: 'https://app.slack.com/team/U01B73XGCKV'
    github:  'https://github.com/Aveline-art'
  picture: 'https://avatars.githubusercontent.com/u/62368440?v=4'
links: 
  - name: GitHub
    url: 'https://github.com/100Automations/GHA-add-issue-to-project/'
  - name: Readme
    url: 'https://github.com/100Automations/GHA-add-issue-to-project/blob/master/README.md'
  - name: Contributing
    url: 'https://github.com/100Automations/GHA-add-issue-to-project/blob/master/CONTRIBUTING.md'
  - name: Support
    url: 'https://github.com/100Automations/GHA-add-issue-to-project/blob/mixin/SUPPORT.md'
  - name: Security
    url: 'https://github.com/100Automations/GHA-add-issue-to-project/blob/mixin/SECURITY.md'
#looking:
# category: 
# - String
# - skill: String
needs: 
 # - maintenance
  - support for users
  - refactoring
# - documentation
  - peer review
#  - to be built
#  - to be researched
#  - takeover
  - advice
status:
#  - in use and ready to deploy
#  -  in use and being refactored
#  - in use and needs further development
#  -  ready to deploy
 -  in development
#  -  ready for development
#  - in ideation
#  - abandoned
seen-in:
# - lock-icon
  -  HackforLA #this needs to be a link eventually
visible: true

---

**Comment by ExperimentsInHonesty** [comment]
This issue is resolved except for the as seen on display is not working https://github.com/100Automations/Website/issues/507
